- name: Service Facts
  service_facts:
  when: ansible_hostname == "db"

- debug:
    var: ansible_facts.services.keys() 
  when: 
    - ansible_hostname == "db"
    - apache in ansible_facts.services.keys()

- name: Stop Apache
  when: 
    - ansible_hostname == "db"  
    - apache in ansible_facts.services.keys()
  systemd:
    name: httpd
    state: stopped

- name: Remove Apache
  when: 
    - ansible_hostname == "db" 
    - apache in ansible_facts.services.keys()
  yum:
    name: httpd
    state: absent