---
  - name: Run Jobs on Dev Servers
    hosts: "{{ group }}"
    gather_facts: "{{ gather_facts }}"
    vars:
      apache: "httpd.service"
    vars_files:
      - "../variables/dev-tasks-values.yaml"
    tasks:
      - include: ../tasks/ping.yaml
      - include: ../tasks/apacheinstallation.yaml
      - include: ../tasks/copyfiles.yaml
      - include: ../tasks/removeapache.yaml